# Generated by Django 4.0.4 on 2022-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
